Proposal for ks-devops && fluxcd integrations for ospp 2022
kubesphere/community pull request #398
Opened 2022-04-19 07:24 UTC by lxm

2022-04-19 07:25 UTC, lxm commented
@LinuxSuRen

2022-04-20 00:55 UTC, LinuxSuRen requested changes
有一些整体需要注意地方：
*  中英文之间需要有空格
* 英文大小写（例如：DevOps）
* 多余空行

对于初次接触 CD 相关技术背景的人，看到这里的背景介绍可能不太清楚这个 proposal 是要做什么，建议给出更详细的内容。

2022-04-20 00:55 UTC, LinuxSuRen commented on sig-advocacy-and-outreach/ospp-2022/ks-devops-fluxcd-integrations.md
> +
这个空行有特殊意义嘛？

2022-04-20 00:56 UTC, LinuxSuRen commented
> @LinuxSuRen

I prefer to ping the @kubesphere/sig-devops instead of me.

2022-04-27 07:35 UTC, faweizhao26 commented
/lgtm
/approve

2022-04-27 07:36 UTC, merged